# Generated by Django 2.2.5 on 2019-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20191219_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='encrypted_img',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='noEncrypt', max_length=42),
            preserve_default=False,
        ),
    ]
