# Generated by Django 3.0.1 on 2019-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20191220_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='encrypted_img',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_img_str',
            field=models.TextField(default='no picture', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.TextField(default='no private key', max_length=256),
            preserve_default=False,
        ),
    ]
